process:
  process_1:
    idx: 0
    name: computer
    state: ready
    priority: 99
    codes:
      - read 2 2
      - write 2 1 0
      - read 3 1
      - read 9 1
      - output
      - input read 2 2
      - output
      - input read 2 1
      - write 2 2 1
      - read 2 1

  process_2:
    idx: 1
    name: filemanager
    state: ready
    priority: 10
    codes:
      - read 4 2
      - write 1 1 0
      - read 2 1
      - output
      - read 5 1
      - input read 2 2
      - read 9 1
      - output
      - input read 2 2
      - output
      - input read 2 1

  process_3:
    idx: 2
    name: aaa
    state: ready
    priority: 5
    codes:
      - read 4 2
      - write 1 1 0
      - read 2 1
      - output
      - read 5 1
      - input read 2 2
      - read 9 1
      - output
      - input read 2 2
      - output
      - input read 2 1

  process_4:
    idx: 3
    name: bbb
    state: ready
    priority: 5
    codes:
      - read 4 2
      - write 1 1 0
      - read 2 1
      - output
      - read 5 1
      - input read 2 2
      - read 9 1
      - output
      - input read 2 2
      - output
      - input read 2 1


  process_5:
    idx: 4
    name: ccc
    state: ready
    priority: 3
    codes:
      - read 4 2
      - write 1 1 0
      - read 2 1
      - output
      - read 5 1
      - input read 2 2
      - read 9 1
      - output
      - input read 2 2
      - output
      - input read 2 1

storage_scheduler:
  memory_size: 3
  storage_size: 80

process_scheduler:
  max_ready_size: 3